package jzodgen

//go:generate go run ../cmd/genjzod

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"

	"github.com/miroir-framework/miroir/go/jzod"
)

const generatedPackageName = "generated"

// GeneratePackage emits a gofmt'd Go file: package clause plus the types from
// [JzodToGoType].
func GeneratePackage(pkg, name string, schema any, env map[string]any) (string, error) {
	return generatePackage(pkg, "// Code generated by jzodgen; DO NOT EDIT.", name, schema, env)
}

func generatePackage(pkg, header, name string, schema any, env map[string]any) (string, error) {
	if pkg == "" {
		pkg = generatedPackageName
	}
	body, err := JzodToGoType(name, schema, env)
	if err != nil {
		return "", err
	}
	src := header + "\n\npackage " + pkg + "\n\n" + body + "\n"
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return "", fmt.Errorf("GeneratePackage format: %w", err)
	}
	return string(formatted), nil
}

// BootstrapSchemaRelPath is the MlSchema JSON used as the Jzod language
// bootstrap (jzodMiroirBootstrapSchema).
const BootstrapSchemaRelPath = "packages/miroir-test-app_deployment-miroir/assets/miroir_data/5e81e1b9-38be-487c-b3e5-53796c57fccf/1e8dab4b-65a3-4686-922e-ce89a2d62aa9.json"

// GenerateBootstrapPackage loads jzodMiroirBootstrapSchema and emits Go types
// for its context plus the root alias.
func GenerateBootstrapPackage() (string, error) {
	doc, err := loadBootstrapSchema()
	if err != nil {
		return "", err
	}
	def := doc["definition"]
	uuid, _ := doc["uuid"].(string)
	env := map[string]any{}
	if uuid != "" {
		env[uuid] = doc
	}
	return generatePackage(
		generatedPackageName,
		"// Code generated by jzodgen from jzodMiroirBootstrapSchema; DO NOT EDIT.\n// Source: "+BootstrapSchemaRelPath,
		"JzodMiroirBootstrapSchema",
		def,
		env,
	)
}

// GeneratedBootstrapRelPath is the committed Go types file under jzod/generated.
const GeneratedBootstrapRelPath = "jzod/generated/jzod_miroir_bootstrap.go"

// WriteBootstrapPackage writes [GenerateBootstrapPackage] to
// [GeneratedBootstrapRelPath].
func WriteBootstrapPackage() (string, error) {
	src, err := GenerateBootstrapPackage()
	if err != nil {
		return "", err
	}
	path := filepath.Join(moduleRoot(), GeneratedBootstrapRelPath)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	if err := os.WriteFile(path, []byte(src), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func loadBootstrapSchema() (map[string]any, error) {
	raw, err := os.ReadFile(filepath.Join(moduleRoot(), BootstrapSchemaRelPath))
	if err != nil {
		return nil, fmt.Errorf("load bootstrap schema: %w", err)
	}
	decoded, err := jzod.Decode(raw)
	if err != nil {
		return nil, fmt.Errorf("decode bootstrap schema: %w", err)
	}
	doc, ok := decoded.(map[string]any)
	if !ok {
		return nil, fmt.Errorf("bootstrap schema is not an object")
	}
	return doc, nil
}

func moduleRoot() string {
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "."
	}
	return filepath.Join(filepath.Dir(file), "..")
}
