package jzodgen_test

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/miroir-framework/miroir/go/jzodgen"
)

func TestGenerateBootstrapPackage(t *testing.T) {
	src, err := jzodgen.GenerateBootstrapPackage()
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(src, "// Code generated by jzodgen from jzodMiroirBootstrapSchema; DO NOT EDIT.") {
		t.Fatalf("missing generated header: %q", src[:min(80, len(src))])
	}
	if !strings.Contains(src, "Source: "+jzodgen.BootstrapSchemaRelPath) {
		t.Fatal("expected bootstrap source path in header")
	}
	if !strings.Contains(src, "package generated\n") {
		t.Fatal("expected package generated")
	}
	wantTypes := []string{
		"JzodArray",
		"JzodAttributeDateValidations",
		"JzodAttributeNumberValidations",
		"JzodAttributePlainDateWithValidations",
		"JzodAttributePlainNumberWithValidations",
		"JzodAttributePlainStringWithValidations",
		"JzodAttributeStringValidations",
		"JzodBaseObject",
		"JzodElement",
		"JzodEnum",
		"JzodEnumAttributeTypes",
		"JzodEnumElementTypes",
		"JzodFunction",
		"JzodIntersection",
		"JzodLazy",
		"JzodLiteral",
		"JzodMap",
		"JzodObject",
		"JzodPlainAttribute",
		"JzodPromise",
		"JzodRecord",
		"JzodReference",
		"JzodSet",
		"JzodTuple",
		"JzodUnion",
		"JzodMiroirBootstrapSchema",
	}
	for _, name := range wantTypes {
		if !strings.Contains(src, "type "+name+" ") {
			t.Errorf("missing type %s", name)
		}
	}
	if strings.Contains(src, "CoreTransformerForBuildPlusRuntimeAny") {
		t.Error("transformer placeholder should map to any, not a named type")
	}
	if strings.Contains(src, "type JzodElement any") {
		t.Error("JzodElement should be a sealed interface, not any")
	}
	if !strings.Contains(src, "type JzodElement interface") {
		t.Error("missing type JzodElement interface")
	}
	if !strings.Contains(src, "func (JzodArray) isJzodElement()") {
		t.Error("missing JzodArray marker method for JzodElement")
	}
	if strings.Contains(src, "Returns *JzodElement") {
		t.Error("optional JzodElement field should not be a pointer to interface")
	}
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "jzod_miroir_bootstrap.go", src, parser.AllErrors); err != nil {
		t.Fatalf("generated Go does not parse: %v", err)
	}
}

func TestGeneratedBootstrapFileMatches(t *testing.T) {
	src, err := jzodgen.GenerateBootstrapPackage()
	if err != nil {
		t.Fatal(err)
	}
	got, err := os.ReadFile(filepath.Join("..", jzodgen.GeneratedBootstrapRelPath))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != src {
		t.Fatal("jzod/generated/jzod_miroir_bootstrap.go is stale; run go run ./cmd/genjzod")
	}
}
